version: '3.9'

services:
  postgres:
    env_file:
      - .env
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./migrations/create-music_library-schema.sql:/docker-entrypoint-initdb.d/create-music_library-schema.sql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}