import { Autocomplete, Box, Button, CircularProgress, FormControl, FormLabel, IconButton, Paper, TextField, Typography, useTheme } from "@mui/material"
import { Add, Done } from "@mui/icons-material";
import { ArtistFormRow } from "./ArtistFormRow";
import { ReleaseFormRow } from "./RealaseFormRow";
import { DurationFormSelection } from "./DurationFormSelection";
import { Controller, FieldValues, SubmitHandler, useFieldArray, useForm } from "react-hook-form";
import { FormErrorHelperText } from "./FormErrorHelperText";
import { FormValue } from "../../common/types/form.type";
import { errorMessage } from "../../common/errors";
import { flattenTimeToSeconds } from "../../common/utils";
import dayjs from "dayjs";
import { useAddSong } from "../../api/apiClient";
import { mutate } from "swr";
import { green } from "@mui/material/colors";
import { PropsWithChildren, forwardRef, useState } from "react";

const genres = [
    "2 tone",
    "2-step garage",
    "4-beat",
    "4x4 garage",
    "8-bit",
    "acapella",
    "acid",
    "acid breaks",
    "acid house",
    "acid jazz",
    "acid rock",
    "acousticana",
    "african rumba",
    "afrobeat",
    "alternative country",
    "alternative dance",
    "alternative hip hop",
    "alternative metal",
    "alternative rock",
    "ambient",
    "ambient house",
    "americana",
    "anarcho punk",
    "anti-folk",
    "apala",
    "ape haters",
    "arab pop",
    "arabesque",
    "arabic pop",
    "argentine rock",
    "ars antiqua",
    "ars nova",
    "art punk",
    "art rock",
    "ashiq",
    "asian american jazz",
    "australian hip hop",
    "australian pub rock",
    "austropop",
    "avant-garde",
    "avant-garde jazz",
    "avant-garde metal",
    "axé",
    "bac-bal",
    "bachata",
    "baggy",
    "baila",
    "baile funk",
    "baisha xiyue",
    "baithak gana",
    "baião",
    "bajourou",
    "bakersfield sound",
    "bakou",
    "bakshy",
    "bal-musette",
    "balakadri",
    "balinese gamelan",
    "balkan pop",
    "ballad",
    "ballata",
    "ballet",
    "bamboo band",
    "bambuco",
    "banda",
    "bangsawan",
    "bantowbol",
    "barndance",
    "baroque pop",
    "batcave",
    "batucada",
    "batuco",
    "batá-rumba",
    "beat",
    "beatboxing",
    "bebop",
    "beiguan",
    "bel canto",
    "bend-skin",
    "benga",
    "bhajan",
    "bhangra",
    "bhangra-wine",
    "bhangragga",
    "bhangramuffin",
    "big band",
    "big beat",
    "biguine",
    "bihu",
    "bikutsi",
    "bitcore",
    "bitpop",
    "black metal",
    "blackened death metal",
    "blue-eyed soul",
    "bluegrass",
    "blues",
    "blues ballad",
    "blues-rock",
    "boogie",
    "boogie woogie",
    "boogie-woogie",
    "bossa nova",
    "brass band",
    "brazilian funk",
    "brazilian jazz",
    "breakbeat",
    "breakbeat hardcore",
    "breakcore",
    "brill building pop",
    "britfunk",
    "british blues",
    "british invasion",
    "britpop",
    "broken beat",
    "brown-eyed soul",
    "brukdown",
    "brutal death metal",
    "bubblegum dance",
    "bubblegum pop",
    "bulerias",
    "bumba-meu-boi",
    "bunraku",
    "burger-highlife",
    "burgundian school",
    "byzantine chant",
    "ca din tulnic",
    "ca pe lunca",
    "ca trù",
    "cabaret",
    "cadence",
    "cadence rampa",
    "cadence-lypso",
    "café-aman",
    "cai luong",
    "cakewalk",
    "calenda",
    "calentanos",
    "calgia",
    "calypso",
    "calypso jazz",
    "calypso-style baila",
    "campursari",
    "canatronic",
    "candombe",
    "canon",
    "canrock",
    "cantata",
    "cante chico",
    "cante jondo",
    "canterbury scene",
    "cantiga",
    "cantique",
    "cantiñas",
    "canto livre",
    "canto nuevo",
    "canto popular",
    "cantopop",
    "canzone napoletana",
    "cape jazz",
    "caracoles",
    "carceleras",
    "cardas",
    "cardiowave",
    "carimbó",
    "cariso",
    "carol",
    "cartageneras",
    "cassette culture",
    "casséy-co",
    "cavacha",
    "caveman",
    "caña",
    "celempungan",
    "cello rock",
    "celtic",
    "celtic fusion",
    "celtic metal",
    "celtic punk",
    "celtic reggae",
    "celtic rock",
    "cha-cha-cha",
    "chakacha",
    "chalga",
    "chamamé",
    "chamber jazz",
    "chamber pop",
    "champeta",
    "changuí",
    "chanson",
    "chant",
    "charanga",
    "charanga-vallenata",
    "charikawi",
    "chastushki",
    "chau van",
    "chemical breaks",
    "chicago blues",
    "chicago house",
    "chicago soul",
    "chicano rap",
    "chicha",
    "chicken scratch",
    "chillout",
    "chillwave",
    "chimurenga",
    "chinese pop",
    "chinese rock",
    "cho-kantrum",
    "chongak",
    "chopera",
    "chorinho",
    "choro",
    "chouval bwa",
    "chowtal",
    "christian alternative",
    "christian black metal",
    "christian hardcore",
    "christian hip hop",
    "christian industrial",
    "christian metal",
    "christian punk",
    "christian r&b",
    "christian rock",
    "christian ska",
    "christmas carol",
    "chumba",
    "chut-kai-pang",
    "chutney",
    "chutney soca",
    "chutney-bhangra",
    "chutney-hip hop",
    "chutney-soca",
    "chylandyk",
    "chzalni",
    "chèo",
    "cigányzene",
    "classic",
    "classic country",
    "classic female blues",
    "classic rock",
    "clicks n cuts",
    "close harmony",
    "cocobale",
    "coimbra fado",
    "coladeira",
    "colombianas",
    "combined rhythm",
    "comedy rap",
    "comedy rock",
    "comic opera",
    "comparsa",
    "compas direct",
    "compas meringue",
    "concert overture",
    "concerto",
    "concerto grosso",
    "congo",
    "conjunto",
    "contemporary christian",
    "contemporary r&b",
    "contonbley",
    "contradanza",
    "cool jazz",
    "corrido",
    "corsican polyphonic song",
    "cothoza mfana",
    "country",
    "country blues",
    "country gospel",
    "country pop",
    "country r&b",
    "country rock",
    "country-rap",
    "countrypolitan",
    "couple de sonneurs",
    "coupé-décalé",
    "cowpunk",
    "crossover jazz",
    "crossover thrash",
    "crossover thrash metal",
    "crunk",
    "crunk&b",
    "crunkcore",
    "crust punk",
    "csárdás",
    "cuarteto",
    "cuban rumba",
    "cuddlecore",
    "cueca",
    "cumbia",
    "cumbia villera",
    "cybergrind",
    "dabka",
    "dadra",
    "daina",
    "dalauna",
    "dance",
    "dance-pop",
    "dance-punk",
    "dance-rock",
    "dancehall",
    "dangdut",
    "dansband",
    "danza",
    "danzón",
    "dark ambient",
    "dark cabaret",
    "dark pop",
    "darkcore",
    "darkstep",
    "darkwave",
    "de ascultat la servici",
    "de codru",
    "de dragoste",
    "de jale",
    "de pahar",
    "death industrial",
    "death metal",
    "death rock",
    "death/doom",
    "deathcore",
    "deathgrind",
    "deathrock",
    "deep funk",
    "deep house",
    "deep soul",
    "degung",
    "delta blues",
    "dementia",
    "desert rock",
    "desi",
    "detroit blues",
    "detroit techno",
    "dhamar",
    "dhimotiká",
    "dhrupad",
    "dhun",
    "digital hardcore",
    "dirge",
    "dirty dutch",
    "dirty rap",
    "dirty rap/pornocore",
    "dirty south",
    "disco",
    "disco house",
    "disco polo",
    "disney",
    "disney hardcore",
    "disney pop",
    "diva house",
    "divine rock",
    "dixieland",
    "dixieland jazz",
    "djambadon",
    "djent",
    "dodompa",
    "doina",
    "dombola",
    "dondang sayang",
    "donegal fiddle tradition",
    "dongjing",
    "doo wop",
    "doom metal",
    "doomcore",
    "downtempo",
    "drag",
    "dream pop",
    "drone doom",
    "drone metal",
    "dronology",
    "drum and bass",
    "dub",
    "dub house",
    "dubanguthu",
    "dubstep",
    "dubtronica",
    "dunedin sound",
    "dunun",
    "dutch jazz",
    "décima",
    "east coast blues",
    "east coast hip hop",
    "easy listening",
    "electric blues",
    "electric folk",
    "electro",
    "electro backbeat",
    "electro hop",
    "electro house",
    "electro punk",
    "electro-industrial",
    "electro-swing",
    "electroclash",
    "electrofunk",
    "electronic",
    "electronic dance",
    "electronic luk thung",
    "electronic rock",
    "electronica",
    "electropop",
    "emo",
    "emo pop",
    "emo rap",
    "emocore",
    "emotronic",
    "enka",
    "eremwu eu",
    "essential rock",
    "ethereal pop",
    "ethereal wave",
    "euro",
    "euro disco",
    "eurobeat",
    "eurodance",
    "europop",
    "eurotrance",
    "eurourban",
    "exotica",
    "experimental noise",
    "experimental pop",
    "experimental rock",
    "extreme metal",
    "ezengileer",
    "fado",
    "falak",
    "fandango",
    "farruca",
    "fife and drum blues",
    "filk",
    "film score",
    "filmi",
    "filmi-ghazal",
    "finger-style",
    "fjatpangarri",
    "flamenco",
    "flamenco rumba",
    "flower power",
    "foaie verde",
    "fofa",
    "folk hop",
    "folk metal",
    "folk pop",
    "folk punk",
    "folk rock",
    "folktronica",
    "forró",
    "franco-country",
    "freak-folk",
    "freakbeat",
    "free improvisation",
    "free jazz",
    "freestyle",
    "freestyle house",
    "freetekno",
    "french pop",
    "frenchcore",
    "frevo",
    "fricote",
    "fuji",
    "fulia",
    "full on",
    "funaná",
    "funeral doom",
    "funk",
    "funk metal",
    "funk rock",
    "funkcore",
    "funky house",
    "fusion jazz",
    "g-funk",
    "gaana",
    "gabba",
    "gabber",
    "gagaku",
    "gaikyoku",
    "gaita",
    "galant",
    "gamad",
    "gambang kromong",
    "gamelan",
    "gamelan angklung",
    "gamelan bang",
    "gamelan bebonangan",
    "gamelan buh",
    "gamelan degung",
    "gamelan gede",
    "gamelan kebyar",
    "gamelan salendro",
    "gamelan selunding",
    "gamelan semar pegulingan",
    "gamewave",
    "gammeldans",
    "gandrung",
    "gangsta rap",
    "gar",
    "garage rock",
    "garrotin",
    "gavotte",
    "gelugpa chanting",
    "gender wayang",
    "gending",
    "gharbi",
    "gharnati",
    "ghazal",
    "ghazal-song",
    "ghetto house",
    "ghettotech",
    "girl group",
    "glam metal",
    "glam punk",
    "glam rock",
    "glitch",
    "gnawa",
    "go-go",
    "goa",
    "goa trance",
    "goombay",
    "goregrind",
    "goshu ondo",
    "gothic metal",
    "gothic rock",
    "granadinas",
    "grebo",
    "gregorian chant",
    "grime",
    "grindcore",
    "groove metal",
    "group sounds",
    "grunge",
    "grupera",
    "guaguanbo",
    "guajira",
    "guasca",
    "guitarra baiana",
    "guitarradas",
    "gumbe",
    "gunchei",
    "gunka",
    "guoyue",
    "gwo ka",
    "gwo ka moderne",
    "gypsy jazz",
    "gypsy punk",
    "gypsybilly",
    "gyu ke",
    "habanera",
    "hajnali",
    "hakka",
    "halling",
    "hambo",
    "hands up",
    "hapa haole",
    "happy hardcore",
    "haqibah",
    "hard",
    "hard bop",
    "hard house",
    "hard rock",
    "hard trance",
    "hardcore hip hop",
    "hardcore metal",
    "hardcore punk",
    "hardcore techno",
    "hardstyle",
    "harepa",
    "harmonica blues",
    "hasaposérviko",
    "heart attack",
    "heartland rock",
    "heavy beat",
    "heavy metal",
    "hesher",
    "hi-nrg",
    "highlands",
    "highlife",
    "highlife fusion",
    "hip hop",
    "hip hop & rap",
    "hip hop soul",
    "hip house",
    "hiplife",
    "hiragasy",
    "hiva usu",
    "hong kong and cantonese pop",
    "hong kong english pop",
    "honky tonk",
    "honkyoku",
    "hora lunga",
    "hornpipe",
    "horror punk",
    "horrorcore",
    "horrorcore rap",
    "house",
    "hua'er",
    "huasteco",
    "huayno",
    "hula",
    "humppa",
    "hunguhungu",
    "hyangak",
    "hymn",
    "hyphy",
    "hát chau van",
    "hát chèo",
    "hát cãi luong",
    "hát tuồng",
    "icaro",
    "idm",
    "ijexá",
    "ilahije",
    "illbient",
    "improvisational",
    "indian pop",
    "indie folk",
    "indie pop",
    "indie rock",
    "indietronica",
    "indo jazz",
    "indo rock",
    "indonesian pop",
    "indoyíftika",
    "industrial death metal",
    "industrial hip-hop",
    "industrial metal",
    "industrial rock",
    "instrumental rock",
    "international latin",
    "iranian pop",
    "irish folk",
    "iscathamiya",
    "isicathamiya",
    "isikhwela jo",
    "island",
    "isolationist",
    "italo dance",
    "italo disco",
    "italo house",
    "itsmeños",
    "izvorna bosanska muzika",
    "j'ouvert",
    "j-fusion",
    "j-pop",
    "j-rock",
    "jaipongan",
    "jaliscienses",
    "jam band",
    "jam rock",
    "jamana kura",
    "jamrieng samai",
    "jangle pop",
    "japanese pop",
    "jarana",
    "jariang",
    "jarochos",
    "jawaiian",
    "jazz",
    "jazz blues",
    "jazz fusion",
    "jazz metal",
    "jazz rap",
    "jazz-funk",
    "jazz-rock",
    "jegog",
    "jenkka",
    "jibaro",
    "jig",
    "jig punk",
    "jing ping",
    "jingle",
    "jit",
    "jitterbug",
    "jive",
    "joged",
    "joged bumbung",
    "joik",
    "jonnycore",
    "joropo",
    "jota",
    "jtek",
    "jug band",
    "jujitsu",
    "juju",
    "juke joint blues",
    "jump blues",
    "jumpstyle",
    "jungle",
    "junkanoo",
    "juré",
    "jùjú",
    "k-pop",
    "kaba",
    "kabuki",
    "kachāshī",
    "kadans",
    "kagok",
    "kagyupa chanting",
    "kaiso",
    "kalamatianó",
    "kalattuut",
    "kalinda",
    "kamba pop",
    "kan ha diskan",
    "kansas city blues",
    "kantrum",
    "kantádhes",
    "kargyraa",
    "karma",
    "kaseko",
    "katajjaq",
    "kawachi ondo",
    "kayōkyoku",
    "ke-kwe",
    "kebyar",
    "kecak",
    "kecapi suling",
    "kertok",
    "khaleeji",
    "khap",
    "khelimaski djili",
    "khene",
    "khoomei",
    "khorovodi",
    "khplam wai",
    "khrung sai",
    "khyal",
    "kilapanda",
    "kinko",
    "kirtan",
    "kiwi rock",
    "kizomba",
    "klape",
    "klasik",
    "klezmer",
    "kliningan",
    "kléftiko",
    "kochare",
    "kolomyjka",
    "komagaku",
    "kompa",
    "konpa",
    "korean pop",
    "koumpaneia",
    "kpanlogo",
    "krakowiak",
    "krautrock",
    "kriti",
    "kroncong",
    "krump",
    "krzesany",
    "kuduro",
    "kulintang",
    "kulning",
    "kumina",
    "kun-borrk",
    "kundere",
    "kundiman",
    "kussundé",
    "kutumba wake",
    "kveding",
    "kvæði",
    "kwaito",
    "kwassa kwassa",
    "kwela",
    "käng",
    "kélé",
    "kĩkũyũ pop",
    "la la",
    "latin american",
    "latin jazz",
    "latin pop",
    "latin rap",
    "lavway",
    "laïko",
    "laïkó",
    "le leagan",
    "legényes",
    "lelio",
    "letkajenkka",
    "levenslied",
    "lhamo",
    "lieder",
    "light rock",
    "likanos",
    "liquid drum&bass",
    "liquid funk",
    "liquindi",
    "llanera",
    "llanto",
    "lo-fi",
    "loki djili",
    "long-song",
    "louisiana blues",
    "louisiana swamp pop",
    "lovers rock",
    "lowercase",
    "lubbock sound",
    "lucknavi thumri",
    "luhya omutibo",
    "luk grung",
    "lullaby",
    "lundu",
    "lundum",
    "m-base",
    "madchester",
    "madrigal",
    "mafioso rap",
    "maglaal",
    "magnificat",
    "mahori",
    "mainstream jazz",
    "makossa",
    "makossa-soukous",
    "malagueñas",
    "malawian jazz",
    "malhun",
    "maloya",
    "maluf",
    "maluka",
    "mambo",
    "manaschi",
    "mandarin pop",
    "manding swing",
    "mango",
    "mangue bit",
    "mangulina",
    "manikay",
    "manila sound",
    "manouche",
    "manzuma",
    "mapouka",
    "mapouka-serré",
    "marabi",
    "maracatu",
    "marga",
    "mariachi",
    "marimba",
    "marinera",
    "marrabenta",
    "martial industrial",
    "martinetes",
    "maskanda",
    "mass",
    "matamuerte",
    "math rock",
    "mathcore",
    "matt bello",
    "maxixe",
    "mazurka",
    "mbalax",
    "mbaqanga",
    "mbube",
    "mbumba",
    "medh",
    "medieval folk rock",
    "medieval metal",
    "meditation",
    "mejorana",
    "melhoun",
    "melhûn",
    "melodic black metal",
    "melodic death metal",
    "melodic hardcore",
    "melodic metalcore",
    "melodic trance",
    "memphis blues",
    "memphis rap",
    "memphis soul",
    "mento",
    "merengue",
    "merengue típico moderno",
    "merengue-bomba",
    "meringue",
    "merseybeat",
    "metal",
    "metalcore",
    "metallic hardcore",
    "mexican pop",
    "mexican rock",
    "mexican son",
    "meykhana",
    "mezwed",
    "miami bass",
    "microhouse",
    "middle of the road",
    "midwest hip hop",
    "milonga",
    "min'yo",
    "mineras",
    "mini compas",
    "mini-jazz",
    "minimal techno",
    "minimalist trance",
    "minneapolis sound",
    "minstrel show",
    "minuet",
    "mirolóyia",
    "modal jazz",
    "modern laika",
    "modern rock",
    "modinha",
    "mohabelo",
    "montuno",
    "monumental dance",
    "mor lam",
    "mor lam sing",
    "morna",
    "motorpop",
    "motown",
    "mozambique",
    "mpb",
    "mugam",
    "multicultural",
    "murga",
    "musette",
    "museve",
    "mushroom jazz",
    "musiqi-e assil",
    "musique concrète",
    "mutuashi",
    "muwashshah",
    "muzak",
    "méringue",
    "música campesina",
    "música criolla",
    "música de la interior",
    "música llanera",
    "música nordestina",
    "música popular brasileira",
    "música tropical",
    "nagauta",
    "nakasi",
    "nangma",
    "nanguan",
    "narcocorrido",
    "nardcore",
    "narodna muzika",
    "nasheed",
    "nashville sound",
    "nashville sound/countrypolitan",
    "national socialist black metal",
    "naturalismo",
    "nederpop",
    "neo soul",
    "neo-classical metal",
    "neo-medieval",
    "neo-prog",
    "neo-psychedelia",
    "neoclassical",
    "neofolk",
    "neotraditional country",
    "nerdcore",
    "neue deutsche härte",
    "neue deutsche welle",
    "new beat",
    "new instrumental",
    "new jack swing",
    "new orleans blues",
    "new orleans jazz",
    "new pop",
    "new prog",
    "new rave",
    "new romantic",
    "new school hip hop",
    "new taiwanese song",
    "new wave",
    "new wave of british heavy metal",
    "new wave of new wave",
    "new weird america",
    "new york blues",
    "new york house",
    "newgrass",
    "nganja",
    "niche",
    "nightcore",
    "nintendocore",
    "nisiótika",
    "no wave",
    "noh",
    "noise pop",
    "noise rock",
    "nongak",
    "norae undong",
    "nortec",
    "norteño",
    "northern soul",
    "nota",
    "nu breaks",
    "nu jazz",
    "nu metal",
    "nu soul",
    "nueva canción",
    "nyatiti",
    "néo kýma",
    "obscuro",
    "oi!",
    "old school hip hop",
    "old-time",
    "oldies",
    "olonkho",
    "oltului",
    "ondo",
    "opera",
    "operatic pop",
    "oratorio",
    "orchestra",
    "organ trio",
    "organic ambient",
    "organum",
    "orgel",
    "oriental metal",
    "ottava rima",
    "outlaw country",
    "p-funk",
    "pagan metal",
    "pagan rock",
    "pagode",
    "paisley underground",
    "palm wine",
    "palm-wine",
    "pambiche",
    "panambih",
    "panchai baja",
    "panchavadyam",
    "pansori",
    "paranda",
    "parang",
    "parody",
    "parranda",
    "partido alto",
    "pasillo",
    "patriotic",
    "peace punk",
    "petenera",
    "peyote song",
    "philadelphia soul",
    "piano blues",
    "piano rock",
    "piedmont blues",
    "pimba",
    "pinoy pop",
    "pinoy rock",
    "pinpeat orchestra",
    "piphat",
    "piyyutim",
    "plainchant",
    "plena",
    "pleng phua cheewit",
    "pleng thai sakorn",
    "political hip hop",
    "polka",
    "polo",
    "polonaise",
    "pols",
    "polska",
    "pong lang",
    "pop",
    "pop folk",
    "pop punk",
    "pop rap",
    "pop rock",
    "pop sunda",
    "pornocore",
    "porro",
    "post disco",
    "post-britpop",
    "post-disco",
    "post-grunge",
    "post-hardcore",
    "post-industrial",
    "post-metal",
    "post-minimalism",
    "post-punk",
    "post-rock",
    "post-romanticism",
    "pow-wow",
    "power electronics",
    "power metal",
    "power noise",
    "power pop",
    "powerviolence",
    "ppongtchak",
    "praise song",
    "program symphony",
    "progressive bluegrass",
    "progressive country",
    "progressive death metal",
    "progressive electronic",
    "progressive folk",
    "progressive house",
    "progressive metal",
    "progressive rock",
    "progressive trance",
    "protopunk",
    "psych folk",
    "psychedelic pop",
    "psychedelic rock",
    "psychedelic trance",
    "psychobilly",
    "punk blues",
    "punk cabaret",
    "punk jazz",
    "punk rock",
    "punta",
    "punta rock",
    "qasidah",
    "qasidah modern",
    "qawwali",
    "quadrille",
    "quan ho",
    "queercore",
    "quiet storm",
    "rada",
    "raga",
    "raga rock",
    "ragga",
    "ragga jungle",
    "raggamuffin",
    "ragtime",
    "rai",
    "rake-and-scrape",
    "ramkbach",
    "ramvong",
    "ranchera",
    "rap",
    "rap metal",
    "rap rock",
    "rapcore",
    "rara",
    "rare groove",
    "rasiya",
    "rave",
    "raw rock",
    "raï",
    "rebetiko",
    "red dirt",
    "reel",
    "reggae",
    "reggae fusion",
    "reggae highlife",
    "reggaefusion",
    "reggaeton",
    "rekilaulu",
    "religious",
    "rembetiko",
    "requiem",
    "rhapsody",
    "rhyming spiritual",
    "rhythm & blues",
    "rhythm and blues",
    "ricercar",
    "riot grrrl",
    "rock",
    "rock and roll",
    "rock en español",
    "rock opera",
    "rockabilly",
    "rocksteady",
    "rococo",
    "rondeaux",
    "ronggeng",
    "roots reggae",
    "roots rock",
    "roots rock reggae",
    "rumba",
    "russian pop",
    "rímur",
    "sabar",
    "sacred harp",
    "sadcore",
    "saibara",
    "sakara",
    "salegy",
    "salsa",
    "salsa erotica",
    "salsa romantica",
    "saltarello",
    "samba",
    "samba-canção",
    "samba-reggae",
    "samba-rock",
    "sambai",
    "sanjo",
    "sato kagura",
    "sawt",
    "saya",
    "scat",
    "schlager",
    "schottisch",
    "schranz",
    "screamo",
    "scrumpy and western",
    "sea shanty",
    "sean nós",
    "second viennese school",
    "seggae",
    "seis",
    "semba",
    "serialism",
    "set dance",
    "sevdalinka",
    "sevillana",
    "shabab",
    "shabad",
    "shalako",
    "shan'ge",
    "shango",
    "shape note",
    "shibuya-kei",
    "shidaiqu",
    "shima uta",
    "shock rock",
    "shoegaze",
    "shoegazer",
    "shoka",
    "shomyo",
    "show tune",
    "sica",
    "siguiriyas",
    "silat",
    "sinawi",
    "singer-songwriter",
    "situational",
    "ska",
    "ska punk",
    "skacore",
    "skald",
    "skate punk",
    "skiffle",
    "slack-key guitar",
    "slide",
    "slowcore",
    "sludge metal",
    "slängpolska",
    "smooth jazz",
    "soca",
    "soft rock",
    "son",
    "son montuno",
    "son-batá",
    "sonata",
    "songo",
    "songo-salsa",
    "sophisti-pop",
    "soukous",
    "soul",
    "soul blues",
    "soul jazz",
    "soundtrack",
    "southern gospel",
    "southern harmony",
    "southern hip hop",
    "southern metal",
    "southern rock",
    "southern soul",
    "space age pop",
    "space rock",
    "spectralism",
    "speed garage",
    "speed metal",
    "speedcore",
    "spirituals",
    "spouge",
    "sprechgesang",
    "square dance",
    "squee",
    "st. louis blues",
    "steelband",
    "stoner metal",
    "stoner rock",
    "straight edge",
    "strathspeys",
    "stride",
    "string",
    "string quartet",
    "suite",
    "sunshine pop",
    "suomirock",
    "super eurobeat",
    "surf ballad",
    "surf instrumental",
    "surf pop",
    "surf rock",
    "swamp blues",
    "swamp pop",
    "swamp rock",
    "swing",
    "swingbeat",
    "sygyt",
    "symphonic black metal",
    "symphonic metal",
    "symphonic poem",
    "symphonic rock",
    "symphony",
    "synthpop",
    "synthpunk",
    "t'ong guitar",
    "taarab",
    "tai tu",
    "taiwanese pop",
    "tala",
    "talempong",
    "tambu",
    "tamburitza",
    "tamil christian keerthanai",
    "tango",
    "tanguk",
    "tappa",
    "tarana",
    "tarantella",
    "taranto",
    "tech",
    "tech house",
    "tech trance",
    "technical death metal",
    "technical metal",
    "techno",
    "technoid",
    "technopop",
    "techstep",
    "techtonik",
    "teen pop",
    "tejano",
    "tekno",
    "tembang sunda",
    "texas blues",
    "thai pop",
    "thillana",
    "thrash metal",
    "thrashcore",
    "thumri",
    "tibetan pop",
    "tiento",
    "timbila",
    "tin pan alley",
    "tinga",
    "tinku",
    "toeshey",
    "togaku",
    "trad jazz",
    "traditional bluegrass",
    "trallalero",
    "trance",
    "tribal house",
    "trikitixa",
    "trip hop",
    "trip rock",
    "trip-hop",
    "tropicalia",
    "tropicalismo",
    "tropipop",
    "truck-driving country",
    "tumba",
    "turbo-folk",
    "turkish pop",
    "turntablism",
    "tuvan throat-singing",
    "twee pop",
    "twist",
    "two tone",
    "táncház",
    "uk garage",
    "uk pub rock",
    "unblack metal",
    "uplifting",
    "uplifting trance",
    "urban cowboy",
    "urban folk",
    "urban jazz",
    "vallenato",
    "vaudeville",
    "venezuela",
    "verbunkos",
    "verismo",
    "viking metal",
    "villanella",
    "virelai",
    "vispop",
    "visual kei",
    "vocal",
    "vocal house",
    "vocal jazz",
    "volksmusik",
    "waila",
    "waltz",
    "wangga",
    "warabe uta",
    "wassoulou",
    "weld",
    "west coast hip hop",
    "west coast jazz",
    "western",
    "western blues",
    "western swing",
    "witch house",
    "wizard rock",
    "wong shadow",
    "wonky pop",
    "wood",
    "work song",
    "world fusion",
    "worldbeat",
    "xoomii",
    "yo-pop",
    "yodeling",
    "yukar",
    "yé-yé",
    "zajal",
    "zapin",
    "zarzuela",
    "zeibekiko",
    "zeuhl",
    "ziglibithy",
    "zouglou",
    "zouk",
    "zouk chouv",
    "zouklove",
    "zydeco"
]

const defaultValues: Partial<FormValue> = {
    title: "",
    hours: 0,
    minutes: 0,
    seconds: 0,
    releasedAs: 'single',
    genres: [],
    albums: [{ albumName: '', trackNumber: 1 }],
    artists: [{
        name: "",
        credit: "PRIMARY"
    }],
}

type FormProps = {
    submitted: Function
}

export const Form = forwardRef<HTMLDivElement, FormProps>(({submitted}, ref) => {

    const theme = useTheme();


    const { data, latestGetSongsKey, mutate: songMutate, isLoading } = useAddSong();
    const [success, setSuccess] = useState(false);

    const { control, formState: {errors}, register, handleSubmit, getValues, reset } = useForm<FormValue>({
        defaultValues: defaultValues,
    });

    const { fields, append, remove } = useFieldArray<FormValue>({
        name: "artists",
        control,
        rules:{
            required: true,
        }
    })

    const renderArtistRows = () => fields.map((field, index) => {
        let nameErrorMessage = errors?.artists?.[index]?.name?.message;

        if (index === 0) {

            return (
                <Box key={field.id} sx={{
                    display: "grid",
                    gridTemplateColumns: "1fr 0fr",
                    gridGap: "10px"
                }}>
                    <FormControl>
                        <TextField 
                            error={!!nameErrorMessage}
                            {...register(`artists.${index}.name`, {
                            required: {
                                value: true,
                                message: errorMessage.required,
                            }
                        })} label="Artist" variant="standard" />
                        <FormErrorHelperText errorMessage={nameErrorMessage} />
                    </FormControl>
                    <IconButton onClick={() => append({name: '', credit:'PRIMARY'})} sx={{ color: theme.palette.primary.main }}>
                        <Add />
                    </IconButton>
                </Box>
            )

        }

        return (
            <ArtistFormRow
                errorMessage={nameErrorMessage}
                control={control}
                key={field.id}
                artistRegister={register(`artists.${index}.name`, {
                    required: {
                        value: true,
                        message: errorMessage.required,
                    }
                })}
                creditRegister={register(`artists.${index}.credit`)}
                deleteHandler={() => remove(index)}
            />
        )
    })

    const onSubmit: SubmitHandler<FieldValues> = async (data: FieldValues) => {
        const {
            hours, 
            seconds, 
            minutes, 
            releaseDate,
            releasedAs,
            albums,
            ...rest
        } = data;
        const duration = flattenTimeToSeconds(hours, minutes, seconds);
        const releaseTimestamp = dayjs(releaseDate).unix();

        const body = {
            ...rest,
            duration,
            releaseTimestamp
        }
        
        await songMutate(body);

        mutate(latestGetSongsKey)

        setSuccess(true);

        setTimeout(() => {
            submitted();
        }, 1000)

    }

    return (
        <Box ref={ref} sx={{maxWidth: "600px"}}>
            <Paper sx={{
                background: theme.palette.primary.main,
                color: theme.palette.common.white,
                textAlign:"center",
                padding: "5px 0",
                marginBottom: "5px",
                borderRadius: "5px 5px 0 0"

            }}>
                <Typography>
                    Add A New Song Listing!
                </Typography>
            </Paper>
            <Paper sx={{
                borderRadius: "0 0 5px 5px",
                border: `2px solid ${theme.palette.primary.main}`
            }}>
                <form 
                    onSubmit={ handleSubmit(onSubmit) }
                    style={{
                        display:'grid', 
                        gridGap: "10px", 
                        gridColumnGap: "40px",
                        justifyContent:'center', 
                        gridTemplateColumns: '1fr',
                        padding: "20px"
                    }} noValidate autoComplete="off
                ">

                    <FormControl>
                        <TextField 
                            error={!!errors.title?.message}
                            {...register("title", {
                                required: {
                                    value: true,
                                    message: errorMessage.required,
                                },
                            })}
                            label="Title" variant="standard"
                        />
                        <FormErrorHelperText errorMessage={errors.title?.message}  />
                    </FormControl>

                    {renderArtistRows()}

                    <Box sx={{
                        display: "grid",
                        gridGap: "10px",
                        alignItems: 'flex-end',
                        [theme.breakpoints.up('md')]:{
                            gridTemplateColumns: "1fr auto auto auto",
                        }
                    }}>
                        <FormLabel>
                            Song Duration:
                        </FormLabel>
                        <DurationFormSelection {...{label: "Hours", id:'hours', maxValue:100, register: register('hours')}} />
                        <DurationFormSelection {...{ label: "Minutes", id: 'minutes', maxValue: 60, register: register('minutes') }} />
                        <DurationFormSelection {...{ 
                            label: "Seconds", 
                            id: 'seconds', 
                            maxValue: 60, 
                            register: register('seconds', {
                                validate: {
                                    hasDurationAboveZero: (v) => {
                                        return v > 0 || getValues().minutes > 0 || getValues().hours > 0 || "Song must have a duration above 0."
                                    }
                                }}
                            ),
                            error: errors?.seconds?.message
                        }} />
                    </Box>

                    <ReleaseFormRow 
                        errors={errors}
                        control={control} 
                        registerDate={register('releaseDate', {
                            required: {
                                value: true,
                                message: errorMessage.required,
                            }
                        })} 
                        registerReleasedAs={register('releasedAs')}
                        register={register} 
                    />

                    <Controller
                        {...register('genres', {
                            required: {
                                value: true,
                                message: errorMessage.required,
                            }
                        })}
                        control={control}
                        render={({
                        field: { onChange },
                        fieldState: { error },
                        }) => 
                        <Autocomplete
                            ref={null}
                            onChange={(event, selectedOptions) => {
                                onChange(selectedOptions);
                            }}
                            sx={{ marginTop: "8px" }}
                            multiple
                            id="size-small-outlined-multi"
                            size="small"
                            options={genres}
                            getOptionLabel={(option) => option}
                            renderInput={(params) => (
                                <TextField error={!!errors?.genres?.message} {...params} label="Select The Genres Of The Track" placeholder="Genre" />
                            )}
                        />}
                    />

                    <Box sx={{
                        position:'relative',
                    }}>
                        <Button 
                            startIcon={success && <Done />}
                            sx={{
                                width:"100%"
                            }}
                            type="submit" 
                            disabled={isLoading || success} 
                            variant="outlined">
                                Submit
                        </Button>
                        {isLoading && (
                            <CircularProgress
                                size={24}
                                sx={{
                                    color: green[500],
                                    position: 'absolute',
                                    top: '50%',
                                    left: '50%',
                                    marginTop: '-12px',
                                    marginLeft: '-12px',
                                }}
                            />
                        )}
                    </Box>


                </form>
            </Paper>
        </Box>
    )
})